### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by Nova-Veritas** [White-Whale-Defi-Platform/white-whale-docs#38]
[ww0-1](https://ww0-1.gitbook.io/untitled/migaloo-docs/smart-contracts/deployments)

<img width="1440" alt="Screenshot 2023-02-16 at 17 06 11" src="https://user-images.githubusercontent.com/125579783/219423091-823c0de7-5ad8-4d56-9fb2-96aad2eb9cee.png">

[white whale docs](https://docs.whitewhale.money/) is down too

**Comment by Sen-Com** [comment]
[https://docs.whitewhale.money](https://docs.whitewhale.money) works now. Thanks for your submission.
